### ISSUE TITLE
Namespace not specified

### ISSUE THREAD

**Issue by vanhaksreng** [pusher/pusher-channels-flutter#177]
A problem occurred configuring project ':pusher_channels_flutter'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

 gradle-8.3

**Comment by SaeedanTechnologies** [comment]
Same issue, I am facing from the past 2 days.

**Comment by sabbir420** [comment]
I am also facing the same issue when I upgraded the gradle and SDKs. Has anyone solved the issue yet?

**Comment by we-prajapati-c001** [comment]
try
```yaml
pusher_channels_flutter:
    git:
      url: https://github.com/kishormainali/pusher-channels-flutter.git
      ref: master
```
